name: notes
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # State management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  bloc: ^8.1.2
  provider: ^6.0.5

  # Network
  internet_connection_checker: ^1.0.0+1

  # Storage
  shared_preferences: ^2.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1

  # Firebase
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5

  # Dependency injection
  get_it: ^7.6.0

  # Functional programming
  dartz: ^0.10.1

  # Utilities
  uuid: ^4.5.1
  flutter_local_notifications: ^18.0.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
